apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-innloggingsinfo-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-innloggingsinfo-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-innloggingsinfo-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-innloggingsinfo-api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  ingresses:
    - "https://tms-innloggingsinfo-api.dev.nav.no/tms-innloggingsinfo-api"
  webproxy: true
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
