apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-innlggingsinfo-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-innlggingsinfo-api-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://tms-innlggingsinfo-api-gcp.dev.nav.no"
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: "1"
      memory: 2560Mi
  accessPolicy:
    outbound:
      rules:
        - application: "app-x"
          namespace: "min-side"
          cluster: "dev-gcp"
